Update test_base64.yml

diff --git a/.github/workflows/test_base64.yml b/.github/workflows/test_base64.yml
--- a/.github/workflows/test_base64.yml
+++ b/.github/workflows/test_base64.yml
@@ -16,10 +16,18 @@ jobs:
       - name: Decode keystore from base64 string to .jks file
         run: |
           echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks
-          # Remove any existing keystore.jks file to avoid conflicts
-          rm -f keystore.jks
-          # Move keystore.jks to the root directory
-          mv keystore.jks $GITHUB_WORKSPACE/keystore.jks
+          # Print the current directory and list its contents for debugging
+          pwd
+          ls -la
+
+      - name: Move keystore.jks to the root directory
+        run: |
+          if [ -f "keystore.jks" ]; then
+            mv keystore.jks $GITHUB_WORKSPACE/keystore.jks
+          else
+            echo "Error: keystore.jks file not found."
+            exit 1
+          fi
           
       # - name: Convert keystore from base64 string to .jks file
       #   run: |
